version: "3.7"

services: 
  flask-video-streaming:
    image: "stonewlg/flask-video-streaming:latest"
    container_name: "flask-video-streaming"
    ports:
      - "5000:5000"
    environment: 
      CAMERA: "opencv"
      OPENCV_CAMERA_SOURCE: "http://192.168.1.100:8080/?action=stream?dummy=param.mjpg"
    volumes: 
      - "./images:/flask-video-streaming/images"
    restart: "unless-stopped"
    networks:
      - "flask-video-streaming-net"

  # nginx:
  #   image: "nginx:1.17.10-alpine"
  #   container_name: "nginx"
  #   ports:
  #     - "8080:80"
  #     - "8443:8443"
  #   environment:
  #     - "NGINX_HOST=robot.chintcloud.net"
  #     - "NGINX_PORT=80"
  #   volumes: 
  #     - "./nginx.conf:/etc/nginx/conf.d/default.conf" 
  #     - "./certs:/certs"     
  #   restart: "unless-stopped"
  #   networks:
  #     - "flask-video-streaming-net"

networks:
  flask-video-streaming-net:
    external: false
    name: "flask-video-streaming-net"
